"use client";
import {useState} from "react";
import {ArrowUpRight,ArrowRight,Copy,BriefcaseBusiness,Globe2,Layers3,ShieldCheck,FileSearch,GitCompareArrows} from "lucide-react";
import {Button} from "@/components/ui/button";
import {AppShell} from "./app-shell";
export function Project(){const[copied,setCopied]=useState(false),[copyError,setCopyError]=useState("");async function copy(){try{await navigator.clipboard.writeText(location.origin+"/project");setCopied(true);setCopyError("");}catch{setCopyError(location.origin+"/project");}}
 return <AppShell active="project"><div className="project-header"><div className="eyebrow">PROJECT / EQUITY RESEARCH × AI</div><h1>기업을 읽는 시선.<br/>시장을 읽는 시선.<br/><span>두 관점을 잇는 리서치.</span></h1><p>Equity Lens는 포트폴리오 분석과 거시경제 분석을 독립적으로 수행하고, 두 결과의 공통점과 충돌을 검토하는 세 에이전트 투자 리서치 프로젝트입니다.</p><div className="flex flex-wrap gap-3 mt-7"><Button asChild><a href="/">시연 콘솔 열기<ArrowRight size={16}/></a></Button><Button variant="outline" onClick={copy}><Copy size={16}/>{copied?"프로젝트 주소 복사됨":"프로젝트 주소 복사"}</Button></div>{copyError&&<p className="break-all">복사할 주소: {copyError}</p>}<div className="project-status"><span>WORKING PROTOTYPE</span>공개 화면은 가상 데이터 · 실제 분석은 개인 환경에서 실행</div></div>
 <section className="project-section"><div className="section-index">01 / APPROACH</div><h2>역할을 나누고, 근거를 연결합니다.</h2><div className="method-grid">{[{icon:BriefcaseBusiness,n:"01",title:"포트폴리오 분석가",text:"보유 종목의 뉴스·시세를 읽고 기업별 변화와 주식 내 비중 집중을 분석합니다.",input:"토스 보유 종목 · Yahoo 뉴스"},{icon:Globe2,n:"02",title:"독립 거시 분석가",text:"보유 종목을 전달받지 않고 금리·물가·성장·환율의 전달 경로를 검토합니다.",input:"중앙은행 자료 · 시장 지표"},{icon:Layers3,n:"03",title:"종합 리서치 편집자",text:"앞선 두 의견을 원자료와 함께 검토하고 충돌 지점과 재검토 조건을 기록합니다.",input:"두 분석 결과 · 출처 목록"}].map(x=><article key={x.n}><div className="flex items-center justify-between"><x.icon size={24}/><span>{x.n}</span></div><h3>{x.title}</h3><p>{x.text}</p><small>{x.input}</small></article>)}</div><p className="method-note">01과 02는 별도의 입력을 사용합니다. 로컬 Ollama 기본값은 메모리 부담을 줄이는 순차 실행입니다. 03은 두 결과가 나온 뒤 실행합니다. 같은 모델을 사용할 경우 편향까지 독립적이라는 뜻은 아닙니다.</p></section>
 <section className="project-section"><div className="section-index">02 / RESEARCH DESIGN</div><h2>결론을 검토할 수 있는 기록.</h2><div className="principles">{[{icon:FileSearch,title:"주장과 출처",text:"사실·해석·조건부 시나리오를 구분하고, 각 주장에 근거와 관측 시각을 연결합니다."},{icon:GitCompareArrows,title:"반대 근거와 충돌",text:"기업 호재와 거시 부담이 동시에 나타날 수 있습니다. 충돌은 숨기지 않고 보고서에 남깁니다."},{icon:ShieldCheck,title:"개인 데이터 분리",text:"이 패키지의 개인 대시보드는 로컬 컴퓨터에서만 사용할 수 있습니다. 시연 화면에는 가상 데이터만 사용합니다."}].map(x=><div key={x.title}><x.icon size={23}/><h3>{x.title}</h3><p>{x.text}</p></div>)}</div></section>
 <section className="linkedin-panel"><div><span className="micro-label">LINKEDIN / PROJECT SHOWCASE</span><h2>리서치 과정 자체를 보여주는 프로젝트.</h2><p>이 소개 페이지 주소를 링크드인 프로필의 프로젝트 링크로 활용할 수 있습니다. 공개된 시연·소개 페이지를 공유할 수 있으며, 실제 계좌 데이터는 공개 화면에 포함되지 않습니다.</p><p className="meta">개인 포트폴리오와 계좌 정보는 이 소개 페이지에 포함되지 않습니다.</p></div><Button asChild variant="outline"><a href="https://www.linkedin.com/" target="_blank" rel="noopener noreferrer">LinkedIn 열기<ArrowUpRight size={17}/></a></Button></section>
 <footer className="page-footer"><span>Equity Lens · Research in progress</span><span>투자 리서치 보조 · 자동 주문 기능 없음</span></footer></AppShell>;
}
