"use client";
import {useCallback,useEffect,useState} from "react";
import {AreaChart,BriefcaseBusiness,Globe2,Layers3,ArrowUpRight,Download,Play,RefreshCw,Info,Link2,ShieldCheck,ArrowRight,AlertTriangle,FileText,Clock3} from "lucide-react";
import {PieChart,Pie,Cell,ResponsiveContainer,Tooltip} from "recharts";
import {Button} from "@/components/ui/button";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from "@/components/ui/table";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from "@/components/ui/empty";
import {Skeleton} from "@/components/ui/skeleton";
import {Toaster,toast} from "sonner";
import {AppShell} from "./app-shell";
import {blankWorkspace,formattedAt,labels,won,type Role,type Workspace,type ResearchReport,packetSchema} from "@/lib/data";
import {demoSnapshot,demoReport} from "@/lib/demo";

const colors=["#b63445","#243e61","#53799a","#92aebf","#c6d4df","#667085"];
const roles:Role[]=["portfolio","macro","synthesis"];
const icons={portfolio:BriefcaseBusiness,macro:Globe2,synthesis:Layers3};
function saveText(r:ResearchReport,demo:boolean){
 const lines=["# Equity Lens · "+(demo?"가상 시연 보고서":"리서치 보고서"),"",`기준: ${r.created_at}`,"",...r.warnings];
 for(const role of roles){const stage=r[role];lines.push("",`## ${labels[role].name} · ${stage.status}`,"",stage.report.summary);for(const f of stage.report.findings)lines.push("",`### ${f.subject}`,f.claim,`분류: ${f.kind} / 근거: ${f.evidence_ids.join(", ")}`,`반대 근거: ${f.counterpoint}`,`재검토 조건: ${f.revisit_when}`);for(const c of stage.report.conflicts)lines.push("",`### ${c.issue}`,`기업: ${c.portfolio_view}`,`거시: ${c.macro_view}`,`평가: ${c.assessment}`);lines.push("","확인 사항",...stage.report.watchlist.map(x=>"- "+x),"","한계",...stage.report.limitations.map(x=>"- "+x));}
 lines.push("","## 출처",...r.sources.map(s=>`- [${s.id}] ${s.title} · ${s.provider}\n  ${s.url}`));
 const url=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/markdown;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=demo?"equity-lens-demo.md":"equity-lens-report.md";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function ResearchConsole({demo=false,user}:{demo?:boolean,user?:string}){
 const [data,setData]=useState<Workspace>(demo?{...blankWorkspace,snapshot:demoSnapshot,report:demoReport}:blankWorkspace);
 const [loading,setLoading]=useState(!demo),[error,setError]=useState("");
 const [role,setRole]=useState<Role>("synthesis"),[sourceIds,setSourceIds]=useState<string[]|null>(null),[busy,setBusy]=useState(false);
 const refresh=useCallback(async(quiet=false)=>{if(demo)return;try{const res=await fetch("/api/workspace",{cache:"no-store"});const d=await res.json() as Workspace & {error?:string;token?:string};if(!res.ok)throw new Error(d.error);setData({...d,...(d.snapshot||d.report?packetSchema.parse({...(d.snapshot?{snapshot:d.snapshot}:{}),...(d.report?{report:d.report}:{})}):{})});setError("");if(!quiet)toast.success("저장된 최신 자료를 불러왔습니다.");}catch(e){setError(e instanceof Error?e.message:"불러오기에 실패했습니다.");}finally{setLoading(false);}},[demo]);
 useEffect(()=>{if(demo)return;void refresh(true);const id=setInterval(()=>{if(!document.hidden)void refresh(true)},10000);return()=>clearInterval(id)},[refresh,demo]);
 useEffect(()=>{
  type MC={registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>};
  const ctx=(document as Document&{modelContext?:MC}).modelContext;if(!ctx)return;const lifecycle=new AbortController();
  Promise.resolve(ctx.registerTool({name:"select_research_agent",title:"에이전트 보고서 선택",description:"표시할 에이전트 보고서를 선택합니다. 새 AI 분석을 요청하지 않습니다.",inputSchema:{type:"object",properties:{role:{type:"string",enum:roles}},required:["role"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const v=input as {role?:Role};if(!v||!roles.includes(v.role as Role))throw new Error("role은 portfolio, macro, synthesis 중 하나여야 합니다.");setRole(v.role!);document.getElementById("report-panel")?.scrollIntoView({behavior:"smooth"});return {selected:v.role,data_mode:demo?"synthetic_demo":"private_workspace"};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();
 },[demo]);
 async function analyze(){if(demo){setRole("synthesis");document.getElementById("report-panel")?.scrollIntoView({behavior:"smooth"});toast.info("미리 작성한 시연 결과입니다. 실제 AI를 호출하지 않습니다.");return;}
  setBusy(true);try{const res=await fetch("/api/jobs",{method:"POST"});const d=await res.json() as Workspace & {error?:string;token?:string};if(!res.ok)throw new Error(d.error);toast.success("분석을 요청했습니다. 수집기가 순서대로 실행합니다.");await refresh(true);}catch(e){toast.error(e instanceof Error?e.message:"분석 요청에 실패했습니다.");}finally{setBusy(false);}
 }
 const s=data.snapshot,r=data.report;
 const online=!!data.heartbeat&&Date.now()-Date.parse(data.heartbeat)<90000;
 const pending=!!data.job&&["queued","running"].includes(data.job.status);
 const topWeight=s?Math.max(0,...s.positions.map(p=>p.weight_pct)):0;
 const sources=r?.sources.filter(s=>!sourceIds||sourceIds.includes(s.id))||[];
 return <AppShell active={demo?"demo":"dashboard"} user={user}><Toaster richColors position="bottom-right"/>
  <header className="page-heading"><div><div className="eyebrow">INVESTMENT RESEARCH CONSOLE</div><h1>{demo?"리서치 콘솔":"내 포트폴리오"}</h1><p>기업과 시장을 따로 읽고, 근거를 함께 검토합니다.</p></div><div className="flex gap-2 flex-wrap">{!demo&&<Button variant="outline" onClick={()=>refresh()} aria-label="최신 자료 불러오기"><RefreshCw size={16}/>새로고침</Button>}<Button onClick={analyze} disabled={busy||pending} className="h-11 px-5"><Play size={15}/>{pending?"분석 진행 중":demo?"시연 보고서 열기":"ANALYZE · 분석 요청"}</Button></div></header>
  <div className={demo?"notice demo-notice":"notice private-notice"}>{demo?<FlaskIcon/>:<ShieldCheck size={17}/>}<span>{demo?<><strong>가상 데이터 시연</strong><span className="notice-divider">|</span>가격·뉴스·보고서는 예시입니다. 실제 계좌나 AI에 연결되어 있지 않습니다.</>:<><strong>나만의 리서치 공간</strong><span className="notice-divider">|</span>마지막 수신 {formattedAt(data.updated_at)} · 화면은 10초마다 확인합니다.</>}</span>{demo&&<a href={import.meta.env.VITE_PUBLIC_DEMO_ONLY==="true"?"/project":"/dashboard"}>{import.meta.env.VITE_PUBLIC_DEMO_ONLY==="true"?"프로젝트 소개":"내 데이터 연결"}<ArrowRight size={15}/></a>}</div>
  {error&&<div role="alert" className="notice error-notice"><AlertTriangle size={18}/>{error}<Button size="sm" variant="outline" onClick={()=>refresh()}>다시 시도</Button></div>}
  {loading?<div className="grid gap-4 md:grid-cols-3 py-6">{[1,2,3].map(n=><Skeleton className="h-32 rounded-xl" key={n}/>)}</div>:<>
  <div className="metrics-grid"><Metric label="주식 평가액 · 현금 제외" value={s?won(s.calculated_equity_value_krw):"—"} foot={demo?"가상 환율 1 USD = 1,400 KRW":"원화 환산 참고치"}/><Metric label="보유 종목" value={s?`${s.positions.length}`:"—"} foot="국내 · 미국 주식" suffix="종목"/><Metric label="최대 종목 비중" value={s?topWeight.toFixed(1)+"%":"—"} foot={s?.positions.find(p=>p.weight_pct===topWeight)?.name||"자료 연결 대기"}/><Metric label="에이전트 상태" value={demo?"DEMO":pending?"분석 중":r?(r.complete?"보고서 완료":"부분 완료"):online?"연결됨":"연결 대기"} foot={demo?"3개의 역할 · 시연 결과":r?"저장된 보고서 상태 · 연결 상태와 별개":online?"연결됨 · 첫 보고서 대기":"결과 파일을 가져오거나 수집기를 실행하세요"} compact/></div>
  <div className="overview-grid">
   <section className="panel portfolio-panel"><div className="panel-heading"><div><h2>포트폴리오 구성</h2><p>주식 평가액 기준 비중</p></div><span className="quiet-badge">{demo?"SAMPLE":s?"MY PORTFOLIO":"NO DATA"}</span></div>
    {s&&s.positions.length>0?<><div className="allocation-area"><div className="donut-wrap"><ResponsiveContainer width="100%" height={206}><PieChart><Pie data={s.positions} dataKey="weight_pct" nameKey="name" innerRadius={69} outerRadius={92} paddingAngle={2} stroke="none">{s.positions.map((p,i)=><Cell key={p.symbol} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={value=>Number(value).toFixed(1)+"%"}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{s.positions.length}</strong><span>HOLDINGS</span></div></div><div className="allocation-legend">{s.positions.slice(0,6).map((p,i)=><div key={p.symbol}><span className="color-key" style={{background:colors[i%colors.length]}}/><span>{p.name}</span><strong>{p.weight_pct.toFixed(1)}<small>%</small></strong></div>)}{s.positions.length>6&&<span className="meta">외 {s.positions.length-6}개 종목은 아래 표에서 확인</span>}</div></div>
    <Table><TableHeader><TableRow><TableHead>종목</TableHead><TableHead className="text-right">가격</TableHead><TableHead className="text-right">수량</TableHead><TableHead className="text-right">비중</TableHead><TableHead className="text-right">시세 기준</TableHead></TableRow></TableHeader><TableBody>{s.positions.map((p,i)=><TableRow key={p.symbol}><TableCell><div className="ticker-cell"><span className="ticker-mark" style={{color:colors[i%colors.length],background:colors[i%colors.length]+"12"}}>{p.symbol.slice(0,2)}</span><div><strong>{p.name}</strong><small>{p.symbol} · {p.market}</small></div></div></TableCell><TableCell className="text-right tabular-nums whitespace-nowrap">{p.currency==="USD"?"$":"₩"}{p.price.toLocaleString("ko-KR",{maximumFractionDigits:2})}</TableCell><TableCell className="text-right tabular-nums">{p.quantity.toLocaleString("ko-KR",{maximumFractionDigits:5})}</TableCell><TableCell className="text-right tabular-nums font-semibold">{p.weight_pct.toFixed(1)}%</TableCell><TableCell className="text-right"><span className="meta whitespace-nowrap">{demo?"가상 가격":formattedAt(p.price_at)}</span></TableCell></TableRow>)}</TableBody></Table></>:<Empty className="min-h-80"><EmptyHeader><BriefcaseBusiness className="mx-auto text-slate-400" size={32}/><EmptyTitle>{s?"보유 주식이 없습니다":"포트폴리오를 연결해 주세요"}</EmptyTitle><EmptyDescription>토스 수집기의 결과 파일을 가져오거나 수집기를 연결하면 종목·비중·기준 시각을 확인할 수 있습니다.</EmptyDescription></EmptyHeader><Button asChild variant="outline"><a href="/connect">데이터 연결<ArrowRight size={15}/></a></Button></Empty>}
    <div className="panel-foot"><Clock3 size={14}/>보유 수량 기준 {formattedAt(s?.as_of)}{demo&&" · 시연 시점"}</div>
   </section>
   <section className="agents-panel"><div className="flex justify-between items-center"><span className="micro-label">AGENT CONSOLE</span><span className="agent-count">3 AGENTS</span></div><h2>세 개의 관점,<br/>하나의 리서치.</h2><p className="agents-intro">기업과 거시 분석을 독립적으로 실행한 뒤, 종합 편집자가 두 결과를 검토합니다.</p><div className="agent-stack">{roles.map((key,i)=>{const Icon=icons[key];return <button key={key} className={"agent-card "+(role===key?"selected":"")} onClick={()=>{setRole(key);document.getElementById("report-panel")?.scrollIntoView({behavior:"smooth"})}}><span className="agent-icon"><Icon size={20}/></span><span className="flex-1"><span className="agent-title"><small>{labels[key].number}</small>{labels[key].name}</span><span className="agent-sub">{labels[key].sub}</span></span><span className="agent-state">{demo?"시연":r?(r[key].status==="ok"?"결과 있음":"실패"):"대기"}</span></button>})}</div><div className="agent-method"><ShieldCheck size={16}/><span>거시 에이전트는 보유 종목을 입력받지 않습니다.</span></div>{!demo&&data.job&&<div className="job-status" role="status">최근 요청: {data.job.status==="queued"?"수집기 대기":data.job.status==="running"?(pending?"수집·분석 진행 중":"응답 지연 · 수집기를 확인하세요"):data.job.status==="complete"?"완료":data.job.status==="partial"?"일부 실패": "실패"}{data.job.error&&<p>{data.job.error}</p>}</div>}</section>
  </div>
  <div className="research-grid"><section className="panel report-panel" id="report-panel"><div className="panel-heading"><div><h2>리서치 보고서</h2><p>{r?formattedAt(r.created_at):"첫 번째 분석을 기다리고 있습니다"}</p></div><Button variant="outline" size="sm" disabled={!r} onClick={()=>r&&saveText(r,demo)}><Download size={15}/>저장</Button></div>
   <Tabs value={role} onValueChange={v=>setRole(v as Role)}><TabsList variant="line" className="report-tabs"><TabsTrigger value="portfolio">01 기업·포트폴리오</TabsTrigger><TabsTrigger value="macro">02 거시경제</TabsTrigger><TabsTrigger value="synthesis">03 종합 판단</TabsTrigger></TabsList>{roles.map(key=><TabsContent key={key} value={key} className="report-content">{r?<><div className="summary-box"><span className="micro-label">{r[key].status==="failed"?"ANALYSIS UNAVAILABLE":"RESEARCH BRIEF"}{demo&&" · DEMO"}</span><p>{r[key].report.summary}</p></div>
    {r[key].report.findings.map((f,i)=><article className="finding" key={i}><div className="finding-title"><h3>{f.subject}</h3><span className="quiet-badge">{({fact:"사실",inference:"해석",scenario:"조건부 시나리오"})[f.kind]}</span></div><p>{f.claim}</p><div className="counterpoint"><span>반대 근거</span><p>{f.counterpoint}</p><span>재검토 조건</span><p>{f.revisit_when}</p></div><div className="finding-bottom"><button onClick={()=>setSourceIds(f.evidence_ids)} className="source-button"><Link2 size={14}/>근거 {f.evidence_ids.length}개 보기<ArrowUpRight size={13}/></button><span className="meta">모델 자체 신뢰도 {({low:"낮음",medium:"보통",high:"높음"})[f.confidence]}</span></div></article>)}
    {!!r[key].report.conflicts.length&&<div className="conflicts"><h3><Layers3 size={16}/>두 분석의 충돌 지점</h3>{r[key].report.conflicts.map((c,i)=><div key={i}><h4>{c.issue}</h4><div className="conflict-views"><p><span>기업 관점</span>{c.portfolio_view}</p><p><span>거시 관점</span>{c.macro_view}</p></div><p className="conflict-assessment">{c.assessment}</p></div>)}</div>}
    {!!r[key].report.watchlist.length&&<div className="next-check"><h3>다음 확인 사항</h3>{r[key].report.watchlist.map((x,i)=><div key={i}><span>{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div>}
    <details className="limitations"><summary>분석 한계 및 수집 경고 ({r[key].report.limitations.length+r.warnings.length+(s?.warnings.length||0)})</summary><ul>{[...r[key].report.limitations,...r.warnings,...(s?.warnings||[])].map((x,i)=><li key={i}>{x}</li>)}</ul></details>
   </>:<Empty className="min-h-80"><EmptyHeader><FileText className="mx-auto text-slate-400" size={32}/><EmptyTitle>아직 분석 보고서가 없습니다</EmptyTitle><EmptyDescription>결과 JSON을 가져오거나 연결된 수집기에 분석을 요청하세요.</EmptyDescription></EmptyHeader><Button asChild variant="outline"><a href="/connect">연결 방법 확인</a></Button></Empty>}</TabsContent>)}</Tabs>
  </section><aside className="evidence-aside"><div className="panel"><div className="panel-heading"><div><h2>뉴스와 근거</h2><p>{demo?"가상 시나리오 2개":`수집 자료 ${r?.sources.length||0}개`}</p></div><BookIcon/></div>{r?.sources.length?<div className="source-feed">{r.sources.slice(0,7).map((s,i)=><button onClick={()=>setSourceIds([s.id])} key={s.id}><span className="meta">{String(i+1).padStart(2,"0")} / {s.provider}</span><strong>{s.title}</strong><span className="source-feed-bottom">{demo?"시연 가정":s.kind==="news"?"뉴스·요약":s.kind==="quote"?"시세":"경제 지표"}<ArrowUpRight size={15}/></span></button>)}<Button variant="ghost" className="w-full" onClick={()=>setSourceIds(r.sources.map(s=>s.id))}>근거 전체 보기<ArrowRight size={15}/></Button></div>:<p className="p-6 text-slate-500 text-sm leading-6">수집된 뉴스·시세·경제지표의 출처가 여기에 표시됩니다.</p>}</div><div className="reading-note"><Info size={18}/><div><h3>판단보다 먼저, 근거 확인</h3><p>각 주장의 출처와 반대 근거를 함께 읽어 주세요. 뉴스 요약과 모델의 해석은 구분해서 표시합니다.</p></div></div></aside></div>
  </>}
  <footer className="page-footer"><span>Equity Lens · Investment Research</span><span>{demo?"시연 데이터 · 실제 수익률 및 뉴스 아님":"시세 발생 시각과 화면 수신 시각은 다를 수 있습니다"}</span></footer>
  <Sheet open={sourceIds!==null} onOpenChange={open=>!open&&setSourceIds(null)}><SheetContent className="overflow-y-auto sm:max-w-xl w-full"><SheetHeader><SheetTitle>분석에 사용한 근거</SheetTitle><SheetDescription>{demo?"가상의 조건을 설명하는 시연 자료입니다. 링크는 기관의 참고 페이지입니다.":"원문·발표 시각과 해석이 일치하는지 확인해 주세요."}</SheetDescription></SheetHeader><div className="px-6 pb-8">{sources.map(s=><article className="source-detail" key={s.id}><span className="meta">{s.provider} · {s.id}</span><h3>{s.title}</h3><p>{s.content}</p><small>{typeof s.observed_at==="string"?formattedAt(s.observed_at):"관측 시각 미확인"}</small><a href={s.url} target="_blank" rel="noreferrer noopener">{demo?"기관 참고 페이지":"출처 열기"}<ArrowUpRight size={16}/></a></article>)}</div></SheetContent></Sheet>
 </AppShell>;
}
function Metric({label,value,foot,suffix,compact}:{label:string,value:string,foot:string,suffix?:string,compact?:boolean}){return <div className="metric"><span>{label}</span><div className={compact?"metric-value compact":"metric-value"}>{value}{suffix&&value!=="—"&&<small>{suffix}</small>}</div><p>{foot}</p></div>}
function FlaskIcon(){return <AreaChart size={18}/>}
function BookIcon(){return <FileText size={18} className="text-slate-400"/>}
