import { snapshotSchema, reportSchema } from "./data";
const at="2026-09-01T07:00:00Z";
export const demoSnapshot=snapshotSchema.parse({as_of:at,valuation_at:at,calculated_equity_value_krw:14000000,scope:"가상 포트폴리오 · 현금 제외",warnings:[],positions:[
 {symbol:"NVDA",name:"NVIDIA",market:"NASDAQ",currency:"USD",quantity:20,price:150,value_krw:4200000,price_at:at,price_quality:"가상 가격"},
 {symbol:"000660",name:"SK하이닉스",market:"KOSPI",currency:"KRW",quantity:14,price:250000,value_krw:3500000,price_at:at,price_quality:"가상 가격"},
 {symbol:"RKLB",name:"Rocket Lab",market:"NASDAQ",currency:"USD",quantity:100,price:20,value_krw:2800000,price_at:at,price_quality:"가상 가격"},
 {symbol:"005930",name:"삼성전자",market:"KOSPI",currency:"KRW",quantity:30,price:70000,value_krw:2100000,price_at:at,price_quality:"가상 가격"},
 {symbol:"XOM",name:"Exxon Mobil",market:"NYSE",currency:"USD",quantity:10,price:100,value_krw:1400000,price_at:at,price_quality:"가상 가격"},
]});
const scenario=(subject:string,claim:string,evidence_ids:string[],counterpoint:string,revisit_when:string)=>({subject,claim,evidence_ids,counterpoint,revisit_when,kind:"scenario",confidence:"low"});
export const demoReport=reportSchema.parse({created_at:at,complete:true,warnings:["실제 뉴스나 AI 호출 결과가 아닙니다. 화면 시연을 위해 작성한 가상 시나리오입니다."],sources:[
 {id:"DEMO-01",provider:"가상 기업 시나리오",title:"AI 반도체 수요가 개선된다면?",content:"반도체 기업의 수요가 개선된다는 가정입니다. 실제 발표나 뉴스가 아닙니다.",url:"https://investor.nvidia.com/",kind:"scenario",observed_at:at},
 {id:"DEMO-02",provider:"가상 거시 시나리오",title:"장기금리가 상승한다면?",content:"장기금리 상승으로 미래 현금흐름의 할인율이 높아진다는 가정입니다. 실제 금리 관측값이 아닙니다.",url:"https://www.federalreserve.gov/monetarypolicy.htm",kind:"scenario",observed_at:at},
],portfolio:{status:"ok",report:{summary:"반도체 수요 개선을 가정해도, 같은 산업에 집중된 비중부터 확인해야 합니다.",findings:[scenario("반도체 · 가상 비중 70%","NVIDIA·SK하이닉스·삼성전자에 투자한 가상 비중은 70%입니다. 동일한 산업 변화가 여러 보유 종목에 동시에 영향을 줄 수 있습니다.",["DEMO-01"],"수요 증가가 가격 하락이나 비용 상승으로 상쇄될 수 있습니다.","실제 기업의 매출 구성과 이익률, 주문 전망을 확인할 때")],conflicts:[],watchlist:["기업별 이익률과 현금흐름 확인","종목 수와 별개로 산업 집중도 검토"],limitations:["가상 포트폴리오와 미리 작성한 시나리오입니다."]}},macro:{status:"ok",report:{summary:"장기금리 상승을 가정하면 성장주의 가치평가와 기업의 조달 비용에 부담이 될 수 있습니다.",findings:[scenario("금리의 전달 경로","할인율 상승은 미래의 이익 비중이 큰 기업에 부담이 될 수 있습니다. 금리 상승의 원인이 성장 개선인지 인플레이션인지 구분해야 합니다.",["DEMO-02"],"성장 전망 개선이 금리 상승을 유발했다면 이익 증가가 일부 부담을 상쇄할 수 있습니다.","실제 금리·물가·고용 지표와 발표 시각이 확보될 때")],conflicts:[],watchlist:["정책금리와 장기 국채금리 구분","물가 둔화와 경기 둔화의 영향 분리"],limitations:["보유 종목과 기업 분석 결과를 입력받지 않는 독립 단계입니다.","실제 거시 지표를 조회하지 않은 시연입니다."]}},synthesis:{status:"ok",report:{summary:"기업의 성장 기대와 금리 부담을 함께 검토합니다. 수요 개선만으로 위험이 줄었다고 단정하기보다, 현금흐름과 집중도를 확인할 필요가 있습니다.",findings:[scenario("기업 호재와 거시 부담의 공존","가상 시나리오에서 사업 수요 개선과 할인율 상승은 동시에 발생합니다. 서로 다른 기간과 전달 경로를 구분해 투자 논리를 재검토합니다.",["DEMO-01","DEMO-02"],"기업의 실제 현금흐름 개선이 할인율 부담보다 크다면 결론이 달라질 수 있습니다.","기업 실적과 실제 장기금리 변화가 함께 확인될 때")],conflicts:[{issue:"수요 개선 vs. 할인율 상승",portfolio_view:"기업 수요 개선이 이익 증가로 연결될 가능성",macro_view:"장기금리 상승이 가치평가에 주는 부담",assessment:"미해결 · 실제 이익과 현금흐름 자료를 확보한 뒤 비교",evidence_ids:["DEMO-01","DEMO-02"]}],watchlist:["기업 실적에서 투자 논리를 뒷받침하는 변화 확인","산업 집중도와 금리 노출을 함께 점검","새 자료가 기존 판단을 바꾸는 조건 기록"],limitations:["이 보고서는 기능 시연용입니다. 실제 투자 판단의 근거로 사용할 수 없습니다."]}}});
